import { Geist, Geist_Mono, Sour_Gummy } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourgummy = Sour_Gummy({
  // variable: "--font-sour-gummy",
  subsets: ['latin']
})

export const metadata = {
  title: "Luanderson ❤️ Tamara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={sourgummy.className}
      >
        {children}
      </body>
    </html>
  );
}
